/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Douglas
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    public JMenu getjMenu1() {
        return mnMenuUsuario;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenuItem getMnCadastrar() {
        return mnCadastrar;
    }

    public JMenuItem getMnExit() {
        return mnExit;
    }

    public JMenuItem getMnVisualizar() {
        return mnVisualizar;
    }

    public JDesktopPane getTelaPrincipal() {
        return telaPrincipal;
    }

    public JLabel getLbTotal() {
        return lbTotal;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public JTextField getTxtAdminRodape() {
        return txtAdminRodape;
    }

    public void setTxtAdminRodape(JTextField txtAdminRodape) {
        this.txtAdminRodape = txtAdminRodape;
    }

    public JTextField getTxtNomeRodape() {
        return txtNomeRodape;
    }

    public void setTxtNomeRodape(JTextField txtNomeRodape) {
        this.txtNomeRodape = txtNomeRodape;
    }

    public JMenuItem getMnVisualizarImagens() {
        return mnVisualizarImagens;
    }

    public void setMnVisualizarImagens(JMenuItem mnVisualizarImagens) {
        this.mnVisualizarImagens = mnVisualizarImagens;
    }

    public JMenu getMnMenuUsuario() {
        return mnMenuUsuario;
    }

    public void setMnMenuUsuario(JMenu mnMenuUsuario) {
        this.mnMenuUsuario = mnMenuUsuario;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPrincipal = new javax.swing.JDesktopPane();
        lbTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeRodape = new javax.swing.JTextField();
        txtAdminRodape = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenuUsuario = new javax.swing.JMenu();
        mnCadastrar = new javax.swing.JMenuItem();
        mnVisualizar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnVisualizarImagens = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        lbTotal.setText("Total de usuários:");

        jLabel1.setText("Nome usuário");

        txtNomeRodape.setEditable(false);
        txtNomeRodape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRodapeActionPerformed(evt);
            }
        });

        txtAdminRodape.setEditable(false);

        mnMenuUsuario.setText("Usuario");

        mnCadastrar.setText("Cadastrar Usuario");
        mnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarActionPerformed(evt);
            }
        });
        mnMenuUsuario.add(mnCadastrar);

        mnVisualizar.setText("Visualizar ");
        mnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarActionPerformed(evt);
            }
        });
        mnMenuUsuario.add(mnVisualizar);

        jMenuBar1.add(mnMenuUsuario);

        jMenu3.setText("Imagens");

        mnVisualizarImagens.setText("Visualizar");
        mnVisualizarImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarImagensActionPerformed(evt);
            }
        });
        jMenu3.add(mnVisualizarImagens);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Sair");

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu2.add(mnExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNomeRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(txtAdminRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdminRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarActionPerformed
    //  new ManterProdutoPresenter();
  
    
    }//GEN-LAST:event_mnCadastrarActionPerformed

    private void mnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarActionPerformed
       
    }//GEN-LAST:event_mnVisualizarActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
       
    }//GEN-LAST:event_mnExitActionPerformed

    private void txtNomeRodapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRodapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRodapeActionPerformed

    private void mnVisualizarImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarImagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnVisualizarImagensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JMenuItem mnCadastrar;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnMenuUsuario;
    private javax.swing.JMenuItem mnVisualizar;
    private javax.swing.JMenuItem mnVisualizarImagens;
    private javax.swing.JDesktopPane telaPrincipal;
    private javax.swing.JTextField txtAdminRodape;
    private javax.swing.JTextField txtNomeRodape;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
